### ISSUE TITLE
Stretch Goal: functionality to download Industry config, AITraffic config, World save

### ISSUE THREAD

**Issue by jackfruh** [sjstein/R8DIUM#78]
Users often want to replicate a server's environment locally so they can practice offline.

The files of interest would be:
Content\V3Routes\Regions\[region]\AutoSaves\Auto Save World.xml
Content\V3Routes\Regions\[region]\Config.ind
Content\V3Routes\Regions\[region]\Traffic.r8

Admins without RDP access may also want these files to test certain recovery scenarios.
For these scenarios, additional world saves would be valuable.
I suspect a similar mechanism used with user listings would work.

(ie:
[1] Auto Save World 2023.10.11 10.00.00.xml
[2] Auto Save World 2023.10.11  09.50.00.xml
[3] Auto Save World 2023.10.11  09.40.00.xml
)

In fact, if you wanted to be super clever...
/Restore_Worldsave 3   
This command could shut down the server, swap the current world save for the 3rd oldest and restart the server.

**Comment by sjstein** [comment]
Seems to be working fine. Can add options in config file specifying which files are available and their locations

**Comment by sjstein** [comment]
New branch for this created: 78_file_download

**Comment by sjstein** [comment]
I think this is a good point to expand on how configparser can take advantage of being a dict to allow a variable number of file types to be defined. Basically a key:value pair for {(short)file name : file path}

e.g.

`{ 'hump' : 'c:\program files\run8studios\content\socal\hump.cfg' }`

**Comment by sjstein** [comment]
add the ability to download the log file and the hostsecurity file to admins only

**Comment by sjstein** [comment]
addressed in merge #134
