### ISSUE TITLE
Too many users exceeds discord message limit

### ISSUE THREAD

**Issue by sjstein** [sjstein/R8DIUM#93]
At some point the message character limit is reached and the /list_users command will fault. Find some way to deal with this.

**Comment by jackfruh** [comment]
30 users per message?

**Comment by sjstein** [comment]
Looks like a 2000 character limit. I quickly tried sending multiple messages with marginal success.

**Comment by sjstein** [comment]
just send a file with a summary:
Discord name, date added, last login, banned status, Notes?

**Comment by sjstein** [comment]
handled in merge #97
